#%RAML 1.0
---

title: Individuals Income
version: P2.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md
 - title: Testing
   content: !include docs/testing.md

mediaType: [ application/json, application/hal+json ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/individuals/income:
  /:
    get:
      displayName: Entry point
      description: This is the entry point to the API and returns one or more links.
      is: [headers.acceptHeader]
      (annotations.sandboxData): !include sandbox/root.md
      (annotations.scope): "read:individuals-income"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:individuals-income" ] } ]
      headers:
        Authorization:
          description: OAuth 2.0 Bearer Token with the read:individuals-income scope.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
      queryParameters:
        matchId:
          description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
          type: string
          example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
      responses:
        200:
          description: The resources available for a matched individual
          body:
            application/json:
              example: !include examples/root.json
              type: !include schemas/root.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST
        404:
          body:
            application/json:
              type: types.errorResponse
              examples:
                NotFound:
                  description: Not found
                  value:
                    code: NOT_FOUND
  /paye:
    get:
      displayName: Retrieve PAYE income history
      description: !include docs/income-endpoint-description.md
      is: [headers.acceptHeader]
      (annotations.sandboxData): !include sandbox/income-request.md
      (annotations.scope): "read:individuals-income-paye"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:individuals-income-paye" ] } ]
      headers:
        Authorization:
          description: OAuth 2.0 Bearer Token with the read:individuals-income-paye scope.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
      queryParameters:
        matchId:
          description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
          type: string
          example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
        fromDate:
          description: The date from when data is requested
          type: string
          required: true
          example: 2016-01-01
        toDate:
          description: The date to when data is requested; if absent it defaults to today's date
          type: string
          required: false
          example: 2017-03-01
      responses:
        200:
          description: The individual PAYE income for the given period
          body:
            application/json:
              example: !include examples/income-response.json
              type: !include schemas/income-response.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST
        404:
          body:
            application/json:
              type: types.errorResponse
              examples:
                NotFound:
                  description: Not found
                  value:
                    code: NOT_FOUND
  /sa:
    get:
      displayName: Retrieve self-assessment footprint
      description: !include docs/income-sa-endpoint-description.md
      is: [headers.acceptHeader]
      (annotations.sandboxData): !include sandbox/income-sa-request.md
      (annotations.scope): "read:individuals-income-sa"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:individuals-income-sa" ] } ]
      headers:
        Authorization:
          description: OAuth 2.0 Bearer Token with the read:individuals-income-sa scope.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
      queryParameters:
        matchId:
          description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
          type: string
          example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
        fromTaxYear:
          description: The tax year from which data is requested
          type: string
          required: true
          example: 2013-14
        toTaxYear:
          description: The tax year until when data is requested; if absent it defaults to the current tax year
          type: string
          required: false
          example: 2015-16
      responses:
        200:
          description: The individual SA income for the given period
          body:
            application/json:
              example: !include examples/income-sa-response.json
              type: !include schemas/income-sa-response.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST
        404:
          body:
            application/json:
              type: types.errorResponse
              examples:
                NotFound:
                  description: Not found
                  value:
                    code: NOT_FOUND

  /sa/additional-information:
    get:
      displayName: Retrieve additional information from self-assessment
      description: !include docs/income-sa-additional-information-endpoint-description.md
      is: [headers.acceptHeader]
      (annotations.sandboxData): !include sandbox/income-sa-request.md
      (annotations.scope): "read:individuals-income-sa-additional-information"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:individuals-income-sa-additional-information" ] } ]
      headers:
        Authorization:
          description: OAuth 2.0 Bearer Token with the read:individuals-income-sa-additional-information scope.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
      queryParameters:
        matchId:
          description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
          type: string
          example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
        fromTaxYear:
          description: The tax year from which data is requested
          type: string
          required: true
          example: 2013-14
        toTaxYear:
          description: The tax year until when data is requested; if absent it defaults to the current tax year
          type: string
          required: false
          example: 2015-16
      responses:
        200:
          description: The individual SA additional information for the given period
          body:
            application/json:
              example: !include examples/income-sa-additional-information-response.json
              type: !include schemas/income-sa-additional-information-response.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST
        404:
          body:
            application/json:
              type: types.errorResponse
              examples:
                NotFound:
                  description: Not found
                  value:
                    code: NOT_FOUND

  /sa/employments:
    get:
      displayName: Retrieve employments income from self-assessment
      description: !include docs/income-sa-employments-endpoint-description.md
      is: [headers.acceptHeader]
      (annotations.sandboxData): !include sandbox/income-sa-request.md
      (annotations.scope): "read:individuals-income-sa-employments"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:individuals-income-sa-employments" ] } ]
      headers:
        Authorization:
          description: OAuth 2.0 Bearer Token with the read:individuals-income-sa-employments scope.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
      queryParameters:
        matchId:
          description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
          type: string
          example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
        fromTaxYear:
          description: The tax year from which data is requested
          type: string
          required: true
          example: 2013-14
        toTaxYear:
          description: The tax year until when data is requested; if absent it defaults to the current tax year
          type: string
          required: false
          example: 2015-16
      responses:
        200:
          description: The individual SA employments income for the given period
          body:
            application/json:
              example: !include examples/income-sa-employments-response.json
              type: !include schemas/income-sa-employments-response.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST
        404:
          body:
            application/json:
              type: types.errorResponse
              examples:
                NotFound:
                  description: Not found
                  value:
                    code: NOT_FOUND

  /sa/foreign:
    get:
      displayName: Retrieve foreign income from self-assessment
      description: !include docs/income-sa-foreign-endpoint-description.md
      is: [headers.acceptHeader]
      (annotations.sandboxData): !include sandbox/income-sa-request.md
      (annotations.scope): "read:individuals-income-sa-foreign"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:individuals-income-sa-foreign" ] } ]
      headers:
        Authorization:
          description: OAuth 2.0 Bearer Token with the read:individuals-income-sa-foreign scope.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
      queryParameters:
        matchId:
          description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
          type: string
          example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
        fromTaxYear:
          description: The tax year from which data is requested
          type: string
          required: true
          example: 2013-14
        toTaxYear:
          description: The tax year until when data is requested; if absent it defaults to the current tax year
          type: string
          required: false
          example: 2015-16
      responses:
        200:
          description: The individual SA foreign income for the given period
          body:
            application/json:
              example: !include examples/income-sa-foreign-response.json
              type: !include schemas/income-sa-foreign-response.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST
        404:
          body:
            application/json:
              type: types.errorResponse
              examples:
                NotFound:
                  description: Not found
                  value:
                    code: NOT_FOUND

  /sa/interests-and-dividends:
    get:
      displayName: Retrieve interests and dividends income from self-assessment
      description: !include docs/income-sa-interests-and-dividends-endpoint-description.md
      is: [headers.acceptHeader]
      (annotations.sandboxData): !include sandbox/income-sa-request.md
      (annotations.scope): "read:individuals-income-sa-interests-and-dividends"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:individuals-income-sa-interests-and-dividends" ] } ]
      headers:
        Authorization:
          description: OAuth 2.0 Bearer Token with the read:individuals-income-sa-interests-and-dividends scope.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
      queryParameters:
        matchId:
          description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
          type: string
          example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
        fromTaxYear:
          description: The tax year from which data is requested
          type: string
          required: true
          example: 2013-14
        toTaxYear:
          description: The tax year until when data is requested; if absent it defaults to the current tax year
          type: string
          required: false
          example: 2015-16
      responses:
        200:
          description: The individual SA interests and dividends income for the given period
          body:
            application/json:
              example: !include examples/income-sa-interests-and-dividends-response.json
              type: !include schemas/income-sa-interests-and-dividends-response.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST
        404:
          body:
            application/json:
              type: types.errorResponse
              examples:
                NotFound:
                  description: Not found
                  value:
                    code: NOT_FOUND
  /sa/other:
    get:
      displayName: Retrieve other income from self-assessment
      description: !include docs/income-sa-other-endpoint-description.md
      is: [headers.acceptHeader]
      (annotations.sandboxData): !include sandbox/income-sa-request.md
      (annotations.scope): "read:individuals-income-sa-other"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:individuals-income-sa-other" ] } ]
      headers:
        Authorization:
          description: OAuth 2.0 Bearer Token with the read:individuals-income-sa-other scope.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
      queryParameters:
        matchId:
          description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
          type: string
          example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
        fromTaxYear:
          description: The tax year from which data is requested
          type: string
          required: true
          example: 2013-14
        toTaxYear:
          description: The tax year until when data is requested; if absent it defaults to the current tax year
          type: string
          required: false
          example: 2015-16
      responses:
        200:
          description: The individual SA other income for the given period
          body:
            application/json:
              example: !include examples/income-sa-other-response.json
              type: !include schemas/income-sa-other-response.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST
        404:
          body:
            application/json:
              type: types.errorResponse
              examples:
                NotFound:
                  description: Not found
                  value:
                    code: NOT_FOUND
  /sa/partnerships:
    get:
      displayName: Retrieve partnerships income from self-assessment
      description: !include docs/income-sa-partnerships-endpoint-description.md
      is: [headers.acceptHeader]
      (annotations.sandboxData): !include sandbox/income-sa-request.md
      (annotations.scope): "read:individuals-income-sa-partnerships"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:individuals-income-sa-partnerships" ] } ]
      headers:
        Authorization:
          description: OAuth 2.0 Bearer Token with the read:individuals-income-sa-partnerships scope.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
      queryParameters:
        matchId:
          description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
          type: string
          example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
        fromTaxYear:
          description: The tax year from which data is requested
          type: string
          required: true
          example: 2013-14
        toTaxYear:
          description: The tax year until when data is requested; if absent it defaults to the current tax year
          type: string
          required: false
          example: 2015-16
      responses:
        200:
          description: The individual SA partnerships income for the given period
          body:
            application/json:
              example: !include examples/income-sa-partnerships-response.json
              type: !include schemas/income-sa-partnerships-response.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST
        404:
          body:
            application/json:
              type: types.errorResponse
              examples:
                NotFound:
                  description: Not found
                  value:
                    code: NOT_FOUND

  /sa/pensions-and-state-benefits:
    get:
      displayName: Retrieve pensions and state benefits income from self-assessment
      description: !include docs/income-sa-pensions-and-state-benefits-endpoint-description.md
      is: [headers.acceptHeader]
      (annotations.sandboxData): !include sandbox/income-sa-request.md
      (annotations.scope): "read:individuals-income-sa-pensions-and-state-benefits"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:individuals-income-sa-pensions-and-state-benefits" ] } ]
      headers:
        Authorization:
          description: OAuth 2.0 Bearer Token with the read:individuals-income-sa-pensions-and-state-benefits scope.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
      queryParameters:
        matchId:
          description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
          type: string
          example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
        fromTaxYear:
          description: The tax year from which data is requested
          type: string
          required: true
          example: 2013-14
        toTaxYear:
          description: The tax year until when data is requested; if absent it defaults to the current tax year
          type: string
          required: false
          example: 2015-16
      responses:
        200:
          description: The individual SA pensions and state benefits income for the given period
          body:
            application/json:
              example: !include examples/income-sa-pensions-and-state-benefits-response.json
              type: !include schemas/income-sa-pensions-and-state-benefits-response.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST
        404:
          body:
            application/json:
              type: types.errorResponse
              examples:
                NotFound:
                  description: Not found
                  value:
                    code: NOT_FOUND

  /sa/self-employments:
    get:
      displayName: Retrieve self-employments income from self-assessment
      description: !include docs/income-sa-self-employments-endpoint-description.md
      is: [headers.acceptHeader]
      (annotations.sandboxData): !include sandbox/income-sa-request.md
      (annotations.scope): "read:individuals-income-sa-self-employments"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:individuals-income-sa-self-employments" ] } ]
      headers:
        Authorization:
          description: OAuth 2.0 Bearer Token with the read:individuals-income-sa-self-employments scope.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
      queryParameters:
        matchId:
          description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
          type: string
          example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
        fromTaxYear:
          description: The tax year from which data is requested
          type: string
          required: true
          example: 2013-14
        toTaxYear:
          description: The tax year until when data is requested; if absent it defaults to the current tax year
          type: string
          required: false
          example: 2015-16
      responses:
        200:
          description: The individual SA self employments income for the given period
          body:
            application/json:
              example: !include examples/income-sa-self-employments-response.json
              type: !include schemas/income-sa-self-employments-response.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST
        404:
          body:
            application/json:
              type: types.errorResponse
              examples:
                NotFound:
                  description: Not found
                  value:
                    code: NOT_FOUND
  /sa/summary:
    get:
      displayName: Retrieve self-assessment tax returns summary
      description: !include docs/income-sa-summary-endpoint-description.md
      is: [headers.acceptHeader]
      (annotations.sandboxData): !include sandbox/income-sa-request.md
      (annotations.scope): "read:individuals-income-sa-summary"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:individuals-income-sa-summary" ] } ]
      headers:
        Authorization:
          description: OAuth 2.0 Bearer Token with the read:individuals-income-sa-summary scope.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
      queryParameters:
        matchId:
          description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
          type: string
          example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
        fromTaxYear:
          description: The tax year from which data is requested
          type: string
          required: true
          example: 2013-14
        toTaxYear:
          description: The tax year until when data is requested; if absent it defaults to the current tax year
          type: string
          required: false
          example: 2015-16
      responses:
        200:
          description: The individual SA summary for the given period
          body:
            application/json:
              example: !include examples/income-sa-summary-response.json
              type: !include schemas/income-sa-summary-response.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST
        404:
          body:
            application/json:
              type: types.errorResponse
              examples:
                NotFound:
                  description: Not found
                  value:
                    code: NOT_FOUND
  /sa/trusts:
    get:
      displayName: Retrieve trusts income from self-assessment
      description: !include docs/income-sa-trusts-endpoint-description.md
      is: [headers.acceptHeader]
      (annotations.sandboxData): !include sandbox/income-sa-request.md
      (annotations.scope): "read:individuals-income-sa-trusts"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:individuals-income-sa-trusts" ] } ]
      headers:
        Authorization:
          description: OAuth 2.0 Bearer Token with the read:individuals-income-sa-trusts scope.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
      queryParameters:
        matchId:
          description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
          type: string
          example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
        fromTaxYear:
          description: The tax year from which data is requested
          type: string
          required: true
          example: 2013-14
        toTaxYear:
          description: The tax year until when data is requested; if absent it defaults to the current tax year
          type: string
          required: false
          example: 2015-16
      responses:
        200:
          description: The individual SA trusts income for the given period
          body:
            application/json:
              example: !include examples/income-sa-trusts-response.json
              type: !include schemas/income-sa-trusts-response.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST
        404:
          body:
            application/json:
              type: types.errorResponse
              examples:
                NotFound:
                  description: Not found
                  value:
                    code: NOT_FOUND
  /sa/uk-properties:
    get:
      displayName: Retrieve UK properties income from self-assessment
      description: !include docs/income-sa-uk-properties-endpoint-description.md
      is: [headers.acceptHeader]
      (annotations.sandboxData): !include sandbox/income-sa-request.md
      (annotations.scope): "read:individuals-income-sa-uk-properties"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:individuals-income-sa-uk-properties" ] } ]
      headers:
        Authorization:
          description: OAuth 2.0 Bearer Token with the read:individuals-income-sa-uk-properties scope.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
      queryParameters:
        matchId:
          description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
          type: string
          example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
        fromTaxYear:
          description: The tax year from which data is requested
          type: string
          required: true
          example: 2013-14
        toTaxYear:
          description: The tax year until when data is requested; if absent it defaults to the current tax year
          type: string
          required: false
          example: 2015-16
      responses:
        200:
          description: The individual SA UK properties income for the given period
          body:
            application/json:
              example: !include examples/income-sa-uk-properties-response.json
              type: !include schemas/income-sa-uk-properties-response.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST
        404:
          body:
            application/json:
              type: types.errorResponse
              examples:
                NotFound:
                  description: Not found
                  value:
                    code: NOT_FOUND
  /sa/source:
    get:
      displayName: Retrieve address and description for each income source
      description: !include docs/income-sa-source-endpoint-description.md
      is: [headers.acceptHeader]
      (annotations.sandboxData): !include sandbox/income-sa-request.md
      (annotations.scope): "read:individuals-income-sa-source"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:individuals-income-sa-source" ] } ]
      headers:
        Authorization:
          description: OAuth 2.0 Bearer Token with the read:individuals-income-sa-source scope.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
      queryParameters:
        matchId:
          description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
          type: string
          example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
        fromTaxYear:
          description: The tax year from which data is requested
          type: string
          required: true
          example: 2013-14
        toTaxYear:
          description: The tax year until when data is requested; if absent it defaults to the current tax year
          type: string
          required: false
          example: 2015-16
      responses:
        200:
          description: The individual SA income sources for the given period
          body:
            application/json:
              example: !include examples/income-sa-source-response.json
              type: !include schemas/income-sa-source-response.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST
        404:
          body:
            application/json:
              type: types.errorResponse
              examples:
                NotFound:
                  description: Not found
                  value:
                    code: NOT_FOUND