#%RAML 1.0
---

title: Individuals Income
version: 2.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md
 - title: Testing
   content: !include docs/testing.md

mediaType: [ application/json, application/hal+json ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/individuals/income:
  /:
    get:
      displayName: Get a list of available endpoints
      description: Use this endpoint to get a list of available endpoints for Individuals Income.
      is: [headers.acceptHeader]
      (annotations.scope): "assigned:scopes"
      securedBy: [ sec.oauth_2_0: { scopes: [ "assigned:scopes" ] } ]
      (annotations.sandboxData): !include sandbox/root.md
      queryParameters:
        matchId:
          description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
          type: string
          example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
      responses:
        200:
          description: The resources available to view an individual's income
          body:
            application/json:
              example: !include examples/root.json
              type: !include schemas/root.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST
        404:
          body:
            application/json:
              type: types.errorResponse
              examples:
                NotFound:
                  description: Not found
                  value:
                    code: NOT_FOUND
  /sa:
    get:
      displayName: Get Self Assessment history
      description: !include docs/income-sa-endpoint-description.md
      is: [headers.acceptHeader]
      (annotations.scope): "assigned:scopes"
      securedBy: [ sec.oauth_2_0: { scopes: [ "assigned:scopes" ] } ]
      (annotations.sandboxData): !include sandbox/income-sa-request.md
      queryParameters:
        matchId:
          description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
          type: string
          example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
        fromTaxYear:
          description: The first tax year to be included in the dataset requested.
          type: string
          required: true
          example: 2018-19
        toTaxYear:
          description: The last tax year to be included in the dataset requested. If missing, it defaults to the current tax year.
          type: string
          required: false
          example: 2019-20
      responses:
        200:
          description: The individual SA income for the given period
          body:
            application/json:
              example: !include examples/income-sa-response.json
              type: !include schemas/income-sa-response.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST
        404:
          body:
            application/json:
              type: types.errorResponse
              examples:
                NotFound:
                  description: Not found
                  value:
                    code: NOT_FOUND
  /paye:
    get:
      displayName: Get PAYE income history
      description: !include docs/income-endpoint-description.md
      is: [headers.acceptHeader]
      (annotations.scope): "assigned:scopes"
      securedBy: [ sec.oauth_2_0: { scopes: [ "assigned:scopes" ] } ]
      (annotations.sandboxData): !include sandbox/income-request.md
      queryParameters:
        matchId:
          description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
          type: string
          example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
        fromDate:
          description: The start date for data requested.
          type: string
          required: true
          example: 2018-01-01
        toDate:
          description: The end date for data requested. If missing, it defaults to today's date.
          type: string
          required: false
          example: 2019-01-01
      responses:
        200:
          description: The individual's PAYE income for the given period
          body:
            application/json:
              example: !include examples/income-response.json
              type: !include schemas/income-response.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST
        404:
          body:
            application/json:
              type: types.errorResponse
              examples:
                NotFound:
                  description: Not found
                  value:
                    code: NOT_FOUND
  /sa/additional-information:
      get:
        displayName: Get additional information from Self Assessment
        description: !include docs/income-sa-additional-information-endpoint-description.md
        is: [headers.acceptHeader]
        (annotations.scope): "assigned:scopes"
        securedBy: [ sec.oauth_2_0: { scopes: [ "assigned:scopes" ] } ]
        (annotations.sandboxData): !include sandbox/income-sa-additional-information-request.md
        queryParameters:
          matchId:
            description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
            type: string
            example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
          fromTaxYear:
            description: The first tax year to be included in the dataset requested.
            type: string
            required: true
            example: 2018-19
          toTaxYear:
            description: The last tax year to be included in the dataset requested. If missing, it defaults to the current tax year.
            type: string
            required: false
            example: 2019-20
        responses:
          200:
            description: The individual’s Self Assessment additional information (SA101) for a requested time period.
            body:
              application/json:
                example: !include examples/income-sa-additional-information-response.json
                type: !include schemas/income-sa-additional-information-response.json
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  BadRequest:
                    description: Invalid request
                    value:
                      code: INVALID_REQUEST
          404:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  NotFound:
                    description: Not found
                    value:
                      code: NOT_FOUND
  /sa/employments:
      get:
        displayName: Get employments income data from Self Assessment
        description: !include docs/income-sa-employments-endpoint-description.md
        is: [headers.acceptHeader]
        (annotations.scope): "assigned:scopes"
        securedBy: [ sec.oauth_2_0: { scopes: [ "assigned:scopes" ] } ]
        (annotations.sandboxData): !include sandbox/income-sa-request-employments.md
        queryParameters:
          matchId:
            description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
            type: string
            example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
          fromTaxYear:
            description: The first tax year to be included in the dataset requested.
            type: string
            required: true
            example: 2018-19
          toTaxYear:
            description: The last tax year to be included in the dataset requested. If missing, it defaults to the current tax year.
            type: string
            required: false
            example: 2019-20
        responses:
          200:
            description: The individual SA employments income for the given period
            body:
              application/json:
                example: !include examples/income-sa-employments-response.json
                type: !include schemas/income-sa-employments-response.json
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  BadRequest:
                    description: Invalid request
                    value:
                      code: INVALID_REQUEST
          404:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  NotFound:
                    description: Not found
                    value:
                      code: NOT_FOUND
  /sa/foreign:
      get:
        displayName: Get foreign income data from Self Assessment
        description: !include docs/income-sa-foreign-endpoint-description.md
        is: [headers.acceptHeader]
        (annotations.scope): "assigned:scopes"
        securedBy: [ sec.oauth_2_0: { scopes: [ "assigned:scopes" ] } ]
        (annotations.sandboxData): !include sandbox/income-sa-request-foreign.md
        queryParameters:
          matchId:
            description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
            type: string
            example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
          fromTaxYear:
            description: The first tax year to be included in the dataset requested.
            type: string
            required: true
            example: 2018-19
          toTaxYear:
            description: The last tax year to be included in the dataset requested. If missing, it defaults to the current tax year.
            type: string
            required: false
            example: 2019-20
        responses:
          200:
            description: An individual’s Self Assessment foreign income data for a requested time period.
            body:
              application/json:
                example: !include examples/income-sa-foreign-response.json
                type: !include schemas/income-sa-foreign-response.json
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  BadRequest:
                    description: Invalid request
                    value:
                      code: INVALID_REQUEST
          404:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  NotFound:
                    description: Not found
                    value:
                      code: NOT_FOUND
  /sa/interests-and-dividends:
      get:
        displayName: Get interest and dividends income data Self Assessment
        description: !include docs/income-sa-interests-and-dividends-endpoint-description.md
        is: [headers.acceptHeader]
        (annotations.scope): "assigned:scopes"
        securedBy: [ sec.oauth_2_0: { scopes: [ "assigned:scopes" ] } ]
        (annotations.sandboxData): !include sandbox/income-sa-request-dividends.md
        queryParameters:
          matchId:
            description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
            type: string
            example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
          fromTaxYear:
            description: The first tax year to be included in the dataset requested.
            type: string
            required: true
            example: 2018-19
          toTaxYear:
            description: The last tax year to be included in the dataset requested. If missing, it defaults to the current tax year.
            type: string
            required: false
            example: 2019-20
        responses:
          200:
            description: The individual's interest and dividends income data Self Assessment
            body:
              application/json:
                example: !include examples/income-sa-interests-and-dividends-response.json
                type: !include schemas/income-sa-interests-and-dividends-response.json
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  BadRequest:
                    description: Invalid request
                    value:
                      code: INVALID_REQUEST
          404:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  NotFound:
                    description: Not found
                    value:
                      code: NOT_FOUND\
  /sa/other:
      get:
        displayName: Get other income data from Self Assessment
        description: !include docs/income-sa-other-endpoint-description.md
        is: [headers.acceptHeader]
        (annotations.scope): "assigned:scopes"
        securedBy: [ sec.oauth_2_0: { scopes: [ "assigned:scopes" ] } ]
        (annotations.sandboxData): !include sandbox/income-sa-request-other.md
        queryParameters:
          matchId:
            description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
            type: string
            example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
          fromTaxYear:
            description: The first tax year to be included in the dataset requested.
            type: string
            required: true
            example: 2018-19
          toTaxYear:
            description: The last tax year to be included in the dataset requested. If missing, it defaults to the current tax year.
            type: string
            required: false
            example: 2019-20
        responses:
          200:
            description: The individual's other income data from Self Assessment
            body:
              application/json:
                example: !include examples/income-sa-other-response.json
                type: !include schemas/income-sa-other-response.json
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  BadRequest:
                    description: Invalid request
                    value:
                      code: INVALID_REQUEST
          404:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  NotFound:
                    description: Not found
                    value:
                      code: NOT_FOUND
  /sa/partnerships:
      get:
        displayName: Get partnerships income data from Self Assessment
        description: !include docs/income-sa-partnerships-endpoint-description.md
        is: [headers.acceptHeader]
        (annotations.scope): "assigned:scopes"
        securedBy: [ sec.oauth_2_0: { scopes: [ "assigned:scopes" ] } ]
        (annotations.sandboxData): !include sandbox/income-sa-request.md
        queryParameters:
          matchId:
            description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
            type: string
            example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
          fromTaxYear:
            description: The first tax year to be included in the dataset requested.
            type: string
            required: true
            example: 2018-19
          toTaxYear:
            description: The last tax year to be included in the dataset requested. If missing, it defaults to the current tax year.
            type: string
            required: false
            example: 2019-20
        responses:
          200:
            description: The individual's partnerships income data from Self Assessment.
            body:
              application/json:
                example: !include examples/income-sa-partnerships-response.json
                type: !include schemas/income-sa-partnerships-response.json
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  BadRequest:
                    description: Invalid request
                    value:
                      code: INVALID_REQUEST
          404:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  NotFound:
                    description: Not found
                    value:
                      code: NOT_FOUND
  /sa/pensions-and-state-benefits:
      get:
        displayName: Get pensions and state benefits income data from Self Assessment
        description: !include docs/income-sa-pensions-and-state-benefits-endpoint-description.md
        is: [headers.acceptHeader]
        (annotations.scope): "assigned:scopes"
        securedBy: [ sec.oauth_2_0: { scopes: [ "assigned:scopes" ] } ]
        (annotations.sandboxData): !include sandbox/income-sa-request-pensions-benefits.md
        queryParameters:
          matchId:
            description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
            type: string
            example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
          fromTaxYear:
            description: The first tax year to be included in the dataset requested.
            type: string
            required: true
            example: 2018-19
          toTaxYear:
            description: The last tax year to be included in the dataset requested. If missing, it defaults to the current tax year.
            type: string
            required: false
            example: 2019-20
        responses:
          200:
            description: The individual's pensions and state benefits income data from Self Assessment
            body:
              application/json:
                example: !include examples/income-sa-pensions-and-state-benefits-response.json
                type: !include schemas/income-sa-pensions-and-state-benefits-response.json
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  BadRequest:
                    description: Invalid request
                    value:
                      code: INVALID_REQUEST
          404:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  NotFound:
                    description: Not found
                    value:
                      code: NOT_FOUND
  /sa/self-employments:
      get:
        displayName: Get self-employments income data from Self Assessment
        description: !include docs/income-sa-self-employments-endpoint-description.md
        is: [headers.acceptHeader]
        (annotations.scope): "assigned:scopes"
        securedBy: [ sec.oauth_2_0: { scopes: [ "assigned:scopes" ] } ]
        (annotations.sandboxData): !include sandbox/income-sa-request-self-employments.md
        queryParameters:
          matchId:
            description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
            type: string
            example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
          fromTaxYear:
            description: The first tax year to be included in the dataset requested.
            type: string
            required: true
            example: 2018-19
          toTaxYear:
            description: The last tax year to be included in the dataset requested. If missing, it defaults to the current tax year.
            type: string
            required: false
            example: 2019-20
        responses:
          200:
            description: The individual's self-employments income data from Self Assessment
            body:
              application/json:
                example: !include examples/income-sa-self-employments-response.json
                type: !include schemas/income-sa-self-employments-response.json
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  BadRequest:
                    description: Invalid request
                    value:
                      code: INVALID_REQUEST
          404:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  NotFound:
                    description: Not found
                    value:
                      code: NOT_FOUND
  /sa/summary:
      get:
        displayName: Get Self Assessment tax returns summary
        description: !include docs/income-sa-summary-endpoint-description.md
        is: [headers.acceptHeader]
        (annotations.scope): "assigned:scopes"
        securedBy: [ sec.oauth_2_0: { scopes: [ "assigned:scopes" ] } ]
        (annotations.sandboxData): !include sandbox/income-sa-request-summary.md
        queryParameters:
          matchId:
            description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
            type: string
            example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
          fromTaxYear:
            description: The first tax year to be included in the dataset requested.
            type: string
            required: true
            example: 2018-19
          toTaxYear:
            description: The last tax year to be included in the dataset requested. If missing, it defaults to the current tax year.
            type: string
            required: false
            example: 2019-20
        responses:
          200:
            description: The individual's Self Assessment tax returns summary for the given period
            body:
              application/json:
                example: !include examples/income-sa-summary-response.json
                type: !include schemas/income-sa-summary-response.json
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  BadRequest:
                    description: Invalid request
                    value:
                      code: INVALID_REQUEST
          404:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  NotFound:
                    description: Not found
                    value:
                      code: NOT_FOUND
  /sa/trusts:
      get:
        displayName: Get trusts income from Self Assessment
        description: !include docs/income-sa-trusts-endpoint-description.md
        is: [headers.acceptHeader]
        (annotations.scope): "assigned:scopes"
        securedBy: [ sec.oauth_2_0: { scopes: [ "assigned:scopes" ] } ]
        (annotations.sandboxData): !include sandbox/income-sa-request-trusts.md
        queryParameters:
          matchId:
            description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
            type: string
            example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
          fromTaxYear:
            description: The first tax year to be included in the dataset requested.
            type: string
            required: true
            example: 2018-19
          toTaxYear:
            description: The last tax year to be included in the dataset requested. If missing, it defaults to the current tax year.
            type: string
            required: false
            example: 2019-20
        responses:
          200:
            description: The individual's trusts income from Self Assessment for the given period
            body:
              application/json:
                example: !include examples/income-sa-trusts-response.json
                type: !include schemas/income-sa-trusts-response.json
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  BadRequest:
                    description: Invalid request
                    value:
                      code: INVALID_REQUEST
          404:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  NotFound:
                    description: Not found
                    value:
                      code: NOT_FOUND
  /sa/uk-properties:
      get:
        displayName: Get UK properties income data from Self Assessment
        description: !include docs/income-sa-uk-properties-endpoint-description.md
        is: [headers.acceptHeader]
        (annotations.scope): "assigned:scopes"
        securedBy: [ sec.oauth_2_0: { scopes: [ "assigned:scopes" ] } ]
        (annotations.sandboxData): !include sandbox/income-sa-request-uk-properties.md
        queryParameters:
          matchId:
            description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
            type: string
            example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
          fromTaxYear:
            description: The first tax year to be included in the dataset requested.
            type: string
            required: true
            example: 2018-19
          toTaxYear:
            description: The last tax year to be included in the dataset requested. If missing, it defaults to the current tax year.
            type: string
            required: false
            example: 2019-20
        responses:
          200:
            description: The individual's UK properties income data from Self Assessment for the given period
            body:
              application/json:
                example: !include examples/income-sa-uk-properties-response.json
                type: !include schemas/income-sa-uk-properties-response.json
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  BadRequest:
                    description: Invalid request
                    value:
                      code: INVALID_REQUEST
          404:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  NotFound:
                    description: Not found
                    value:
                      code: NOT_FOUND
  /sa/source:
      get:
        displayName: Get details for each income source
        description: !include docs/income-sa-source-endpoint-description.md
        is: [headers.acceptHeader]
        (annotations.scope): "assigned:scopes"
        securedBy: [ sec.oauth_2_0: { scopes: [ "assigned:scopes" ] } ]
        (annotations.sandboxData): !include sandbox/income-sa-request-source.md
        queryParameters:
          matchId:
            description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
            type: string
            example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
          fromTaxYear:
            description: The first tax year to be included in the dataset requested.
            type: string
            required: true
            example: 2018-19
          toTaxYear:
            description: The last tax year to be included in the dataset requested. If missing, it defaults to the current tax year.
            type: string
            required: false
            example: 2019-20
        responses:
          200:
            description: The individual's details for each income source for the given period
            body:
              application/json:
                example: !include examples/income-sa-source-response.json
                type: !include schemas/income-sa-source-response.json
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  BadRequest:
                    description: Invalid request
                    value:
                      code: INVALID_REQUEST
          404:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  NotFound:
                    description: Not found
                    value:
                      code: NOT_FOUND
  /sa/further-details:
        get:
          displayName: Get further details for income from Self Assessment
          description: !include docs/income-sa-further-details-endpoint-description.md
          is: [headers.acceptHeader]
          (annotations.scope): "assigned:scopes"
          securedBy: [ sec.oauth_2_0: { scopes: [ "assigned:scopes" ] } ]
          (annotations.sandboxData): !include sandbox/income-sa-request-further-details.md
          queryParameters:
            matchId:
              description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
              type: string
              example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
            fromTaxYear:
              description: The first tax year to be included in the dataset requested.
              type: string
              required: true
              example: 2018-19
            toTaxYear:
              description: The last tax year to be included in the dataset requested. If missing, it defaults to the current tax year.
              type: string
              required: false
              example: 2019-20
          responses:
            200:
              description: The individual's further details for income from Self Assessment for the given period
              body:
                application/json:
                  example: !include examples/income-sa-further-details-response.json
                  type: !include schemas/income-sa-further-details-response.json
            400:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    BadRequest:
                      description: Invalid request
                      value:
                        code: INVALID_REQUEST
            404:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    NotFound:
                      description: Not found
                      value:
                        code: NOT_FOUND